version: '3.8'

services:
  # Servicio 1: Nuestra API en Go
  api:
    build: .
    container_name: api-global-backend
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    # Inyecta todas las variables del archivo .env automáticamente
    env_file:
      - .env
    networks:
      - universitas-net

# Definición de red para los contenedores (por si a futuro agregas Redis u otro servicio)
networks:
  universitas-net:
    driver: bridge