version: '3.8'

services:
  # Servicio 1: Nuestra API en Go
  api:
    build: .             # Construye usando el Dockerfile del directorio actual
    container_name: api-global-backend
    ports:
      - "8080:8080"      # Mapea puerto 8080 local al 8080 del contenedor
    depends_on:
      db:
        condition: service_healthy              # Espera a que la BD inicie antes de arrancar (básico)
    environment:
      - DB_HOST=db       # ¡OJO! Aquí el host es el nombre del servicio, no 'localhost'
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=universitas_db
      - DB_PORT=5432
    networks:
      - universitas-net

  # Servicio 2: Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: api-global-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: universitas_db
    ports:
      - "5433:5432"      # Exponemos el puerto 5432 para que puedas entrar con PGADMIN local
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia de datos
    networks:
      - universitas-net
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d universitas_db"]
      interval: 5s
      timeout: 5s
      retries: 5

# Definición de volúmenes para que los datos sobrevivan al apagar Docker
volumes:
  postgres_data:

# Definición de red para que los contenedores se vean entre sí
networks:
  universitas-net:
    driver: bridge