// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Jose"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/economia/bcv": {
            "get": {
                "description": "Retorna el valor actual del Dólar y Euro oficial.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Economia"
                ],
                "summary": "Obtener tasas del BCV (Dólar y Euro)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.GenericResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.BCVResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.GenericResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/economia/ucauu": {
            "get": {
                "description": "Retorna el último valor registrado de la unidad UCAUU",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Economia"
                ],
                "summary": "Obtener última UCAUU",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UCAUUResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.GenericResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Permite registrar el valor de la UCAUU del día actual. Si ya existe, lo actualiza.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Economia"
                ],
                "summary": "Registrar o Actualizar UCAUU",
                "parameters": [
                    {
                        "description": "Valor de la UCAUU",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUCAUURequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.GenericResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.GenericResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.GenericResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/territorio/estados": {
            "get": {
                "description": "Retorna la lista de todos los estados de Venezuela",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Territorio"
                ],
                "summary": "Obtener todos los estados",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.GenericResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.EstadoResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.GenericResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/territorio/estados/{estado_id}/ciudades": {
            "get": {
                "description": "Retorna la lista de ciudades pertenecientes a un estado específico",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Territorio"
                ],
                "summary": "Obtener ciudades por estado",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Estado",
                        "name": "estado_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.GenericResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.CiudadResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.GenericResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.GenericResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/territorio/estados/{estado_id}/municipios": {
            "get": {
                "description": "Retorna la lista de municipios pertenecientes a un estado específico",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Territorio"
                ],
                "summary": "Obtener municipios por estado",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Estado",
                        "name": "estado_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.GenericResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.MunicipioResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.GenericResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.GenericResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/territorio/estados/{estado_id}/tribunales": {
            "get": {
                "description": "Retorna la lista de tribunales de categoría Superior y Primera Instancia pertenecientes a un estado",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Territorio"
                ],
                "summary": "Obtener tribunales estadales por estado",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Estado",
                        "name": "estado_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.GenericResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.TribunalResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.GenericResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.GenericResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/territorio/municipios/{municipio_id}/parroquias": {
            "get": {
                "description": "Retorna la lista de parroquias pertenecientes a un municipio específico",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Territorio"
                ],
                "summary": "Obtener parroquias por municipio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Municipio",
                        "name": "municipio_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.GenericResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.ParroquiaResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.GenericResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.GenericResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/territorio/municipios/{municipio_id}/tribunales": {
            "get": {
                "description": "Retorna la lista de tribunales de categoría Municipio asociados a un municipio específico, incluyendo los compartidos con otros municipios",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Territorio"
                ],
                "summary": "Obtener tribunales municipales por municipio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Municipio",
                        "name": "municipio_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.GenericResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.TribunalResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.GenericResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.GenericResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.BCVResponse": {
            "type": "object",
            "properties": {
                "eur": {
                    "type": "number",
                    "example": 39.1234
                },
                "fecha": {
                    "type": "string",
                    "example": "2026-03-20T00:00:00Z"
                },
                "usd": {
                    "type": "number",
                    "example": 36.4521
                }
            }
        },
        "dto.CiudadResponse": {
            "type": "object",
            "properties": {
                "estado_id": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "nombre": {
                    "type": "string",
                    "example": "Barquisimeto"
                }
            }
        },
        "dto.CreateUCAUURequest": {
            "type": "object",
            "required": [
                "valor"
            ],
            "properties": {
                "valor": {
                    "description": "validate:\"required,gt=0\" asegura que el campo venga y sea mayor a cero",
                    "type": "number",
                    "example": 35.5
                }
            }
        },
        "dto.EstadoResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "nombre": {
                    "type": "string",
                    "example": "Lara"
                }
            }
        },
        "dto.GenericResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Operación exitosa"
                }
            }
        },
        "dto.MunicipioResponse": {
            "type": "object",
            "properties": {
                "estado_id": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer",
                    "example": 10
                },
                "nombre": {
                    "type": "string",
                    "example": "Iribarren"
                }
            }
        },
        "dto.ParroquiaResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 50
                },
                "municipio_id": {
                    "type": "integer",
                    "example": 10
                },
                "nombre": {
                    "type": "string",
                    "example": "Catedral"
                }
            }
        },
        "dto.TribunalResponse": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string",
                    "example": "Superior"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "nombre": {
                    "type": "string",
                    "example": "Corte de Apelaciones Sala 1"
                }
            }
        },
        "dto.UCAUUResponse": {
            "type": "object",
            "properties": {
                "fecha": {
                    "type": "string",
                    "example": "2026-03-20T10:00:00Z"
                },
                "valor": {
                    "type": "number",
                    "example": 35.5
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API Global Universitas",
	Description:      "API centralizada para indicadores económicos y territoriales.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
